"""Add initial tables

Revision ID: 6e109cf7d6f6
Revises: 
Create Date: 2022-09-13 18:46:41.559759

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6e109cf7d6f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_name", sa.String(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("datestamp", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("skill_name", "page_number", "datestamp"),
    )
    op.create_index(op.f("ix_page_datestamp"), "page", ["datestamp"], unique=False)
    op.create_index(op.f("ix_page_page_number"), "page", ["page_number"], unique=False)
    op.create_index(op.f("ix_page_skill_name"), "page", ["skill_name"], unique=False)
    op.create_table(
        "score",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("skill_name", sa.String(), nullable=False),
        sa.Column("player_name", sa.String(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["page.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_score_page_id"), "score", ["page_id"], unique=False)
    op.create_index(
        op.f("ix_score_player_name"), "score", ["player_name"], unique=False
    )
    op.create_index(op.f("ix_score_skill_name"), "score", ["skill_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_score_skill_name"), table_name="score")
    op.drop_index(op.f("ix_score_player_name"), table_name="score")
    op.drop_index(op.f("ix_score_page_id"), table_name="score")
    op.drop_table("score")
    op.drop_index(op.f("ix_page_skill_name"), table_name="page")
    op.drop_index(op.f("ix_page_page_number"), table_name="page")
    op.drop_index(op.f("ix_page_datestamp"), table_name="page")
    op.drop_table("page")
    # ### end Alembic commands ###
